server:
  port: 8030

spring:
  application:
    name: mall-order
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.12:3306/mall-oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.12:8848
      serverAddr: 10.211.55.12:8848
      # 以下配置项必须填写
      username: 'nacos'
      password: 'nacos'
#      config:
#        extension-configs:
#          - data-id: mybatis.yaml
#          - group: dev
  config:
    import:
      - nacos:mall-order.yaml?refresh=true&group=DEFAULT_GROUP

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
